// Generates e2e/fixtures/aims-mixed-grch38.vcf: a synthetic single-sample
// GRCh38 VCF with one row at every position of the shipped ancestry marker
// panel (`data/ref/aims.json`), so the ancestry page's shown state (map,
// toggle, chips, table, panel) has an end-to-end test. It describes no real
// person: every genotype is drawn from a seeded pseudo-random generator
// (mulberry32, the same draw `src/lib/genome/admixture.test.ts` uses) with
// each allele copy taken from one reference superpopulation by the mixing
// weights below, then ALT with that population's panel frequency.
//
//   pnpm exec tsx e2e/fixtures/generate-aims-vcf.ts
//
// The output is byte-identical across runs. After writing, the script parses
// the file with the real VCF parser and runs the real estimator over the
// parsed records, and fails unless the result has at least MIN_MARKERS
// usable markers (the map is shown, not grey) and at least one region below
// the well-supported threshold (the toggle hides something). The VCF parser
// drops homozygous-reference rows, so "markers used" counts the panel
// positions that carry at least one ALT allele.
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { MIN_MARKERS } from "../../src/lib/ancestry/panel";
import { WELL_SUPPORTED_MIN } from "../../src/lib/ancestry/present";
import { AIMS, POPS, estimateAdmixture, type AdmixtureResult, type Pop } from "../../src/lib/genome/admixture";
import { parseVcf } from "../../src/lib/genome/parsers/vcf";

export const FIXTURE_NAME = "aims-mixed-grch38.vcf";

/** Mixing weights per allele copy (design §6.2): one region falls below 2%. */
export const WEIGHTS: Record<Pop, number> = { AFR: 0.3, AMR: 0, EAS: 0.1, EUR: 0.6, SAS: 0 };

/**
 * The seed is the first one (searched upward from 1) whose draw satisfies
 * both checks in `verify()`, leaves at least three regions at or above the
 * threshold (both toggle states list more than one region), and puts one
 * region strictly between 0 and the threshold (the hidden chip is not 0.0%).
 * Its draw also leaves one region at exactly 0, which renders as a dashed
 * hairline when the toggle is off.
 */
export const SEED = 13;

/** Deterministic PRNG (mulberry32). */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** One diploid genotype as a VCF GT field: each copy picks a superpopulation by weight, then ALT with its frequency. */
function drawGt(rnd: () => number, freqs: Record<Pop, number>): string {
  const copies: number[] = [];
  for (let copy = 0; copy < 2; copy++) {
    let u = rnd();
    let pop: Pop = POPS[POPS.length - 1];
    for (const p of POPS) {
      u -= WEIGHTS[p];
      if (u < 0) {
        pop = p;
        break;
      }
    }
    copies.push(rnd() < freqs[pop] ? 1 : 0);
  }
  return copies.sort().join("/");
}

/** The fixture's lines (no trailing newline on the last line). */
export function buildAimsVcf(seed: number): string[] {
  const rnd = mulberry32(seed);
  const rows = [...AIMS]
    .sort((a, b) => a.chrom - b.chrom || a.pos38 - b.pos38)
    .map((m) => [`chr${m.chrom}`, String(m.pos38), m.rsid, m.ref, m.alt, "50", "PASS", ".", "GT", drawGt(rnd, m.freqs)].join("\t"));
  return [
    "##fileformat=VCFv4.2",
    `##source=Inherit deterministic synthetic fixture; no real person; seed ${seed}; generated by e2e/fixtures/generate-aims-vcf.ts`,
    "##reference=GRCh38",
    '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">',
    ["#CHROM", "POS", "ID", "REF", "ALT", "QUAL", "FILTER", "INFO", "FORMAT", "SAMPLE1"].join("\t"),
    ...rows,
  ];
}

async function* asLines(lines: string[]): AsyncIterable<string> {
  for (const line of lines) yield line;
}

/** What the process route would store for this fixture: the real parser, then the real estimator. */
export async function estimateFixture(lines: string[]): Promise<AdmixtureResult> {
  const parsed = await parseVcf(asLines(lines));
  const byPos = new Map(parsed.records.map((r) => [`${r.chrom}:${r.pos}`, r.genotype]));
  return estimateAdmixture((chrom, pos) => byPos.get(`${chrom}:${pos}`) ?? null);
}

export interface FixtureCheck {
  ok: boolean;
  markersUsed: number;
  proportions: Record<Pop, number>;
  belowThreshold: Pop[];
  reasons: string[];
}

export function verify(result: AdmixtureResult): FixtureCheck {
  const belowThreshold = POPS.filter((pop) => result.proportions[pop] < WELL_SUPPORTED_MIN);
  const reasons: string[] = [];
  if (result.markersUsed < MIN_MARKERS) {
    reasons.push(`markersUsed ${result.markersUsed} is below MIN_MARKERS ${MIN_MARKERS}: the map would be grey`);
  }
  if (belowThreshold.length === 0) {
    reasons.push(`no region is below the well-supported threshold ${WELL_SUPPORTED_MIN}: the toggle would hide nothing`);
  }
  return { ok: reasons.length === 0, markersUsed: result.markersUsed, proportions: result.proportions, belowThreshold, reasons };
}

async function main() {
  const lines = buildAimsVcf(SEED);
  const result = await estimateFixture(lines);
  const check = verify(result);
  if (!check.ok) {
    console.error(`fixture check failed for seed ${SEED}:\n  - ${check.reasons.join("\n  - ")}`);
    process.exitCode = 1;
    return;
  }
  const text = `${lines.join("\n")}\n`;
  const target = path.join(path.dirname(fileURLToPath(import.meta.url)), FIXTURE_NAME);
  fs.writeFileSync(target, text);
  const sha256 = crypto.createHash("sha256").update(text).digest("hex");
  console.log(`wrote ${path.relative(process.cwd(), target)} (${text.length} bytes, ${lines.length - 5} rows)`);
  console.log(`markers used: ${check.markersUsed} of ${AIMS.length} (minimum ${MIN_MARKERS})`);
  console.log(`proportions: ${POPS.map((pop) => `${pop} ${check.proportions[pop].toFixed(3)}`).join(", ")}`);
  console.log(`below ${WELL_SUPPORTED_MIN}: ${check.belowThreshold.join(", ")}`);
  console.log(`sha256: ${sha256}`);
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  void main();
}
