import type { FileKind } from "../src/lib/genome/types";

/** Invented calls at the same three GRCh38 loci in every representation.
 * No participant export or publicly released individual's data is used. */
const calls = [
  { rsid: "rs4988235", chrom: "2", pos: 135851076, ref: "G", alt: "A", gt: "1/1", alleles: "AA" },
  { rsid: "rs1815739", chrom: "11", pos: 66560624, ref: "C", alt: "T", gt: "0/1", alleles: "CT" },
  { rsid: "rs762551", chrom: "15", pos: 74749576, ref: "C", alt: "A", gt: "0/1", alleles: "AC" },
];

function vcf(symbol?: string) {
  const header = "##fileformat=VCFv4.3\n##source=Inherit invented format-test calls\n##reference=GRCh38\n"
    + (symbol ? `##ALT=<ID=${symbol.slice(1, -1)},Description="Unspecified alternative allele">\n` : "")
    + "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSYNTHETIC\n";
  const block = symbol ? `1\t100\t.\tA\t${symbol}\t50\tPASS\tEND=199\tGT\t0/0\n` : "";
  return header + block + calls.map(call => [call.chrom, call.pos, call.rsid, call.ref,
    call.alt + (symbol ? `,${symbol}` : ""), 50, "PASS", ".", "GT", call.gt].join("\t")).join("\n") + "\n";
}

export const syntheticOwnUploadFormats: readonly { id: string; kind: FileKind; text: string }[] = [
  { id: "23andme", kind: "array_23andme", text:
    "# This data file generated by 23andMe format test; invented calls\n# build 38\n# rsid\tchromosome\tposition\tgenotype\n"
    + calls.map(call => [call.rsid, call.chrom, call.pos, call.alleles].join("\t")).join("\n") + "\n" },
  { id: "ancestry", kind: "array_ancestry", text:
    "#AncestryDNA format test; invented calls\n# build 38\nrsid\tchromosome\tposition\tallele1\tallele2\n"
    + calls.map(call => [call.rsid, call.chrom, call.pos, ...call.alleles].join("\t")).join("\n") + "\n" },
  { id: "myheritage", kind: "array_myheritage", text:
    '# MyHeritage format test; invented calls\n# build 38\n"RSID","CHROMOSOME","POSITION","RESULT"\n'
    + calls.map(call => [call.rsid, call.chrom, call.pos, call.alleles].map(value => `"${value}"`).join(",")).join("\n") + "\n" },
  { id: "ftdna", kind: "array_ftdna", text:
    "# Invented calls; build 38\nRSID,CHROMOSOME,POSITION,RESULT\n"
    + calls.map(call => [call.rsid, call.chrom, call.pos, call.alleles].join(",")).join("\n") + "\n" },
  { id: "vcf", kind: "vcf", text: vcf() },
  { id: "gvcf-non-ref", kind: "gvcf", text: vcf("<NON_REF>") },
  { id: "gvcf-unspecified", kind: "gvcf", text: vcf("<*>") },
];
