/**
 * What the ancestry surface's range sentence is allowed to say.
 *
 * `src/copy/ancestry.ts` tells a reader the true share fell inside the range
 * "about nine times in ten". That is a claim about a person's ancestry result
 * and it is not allowed to be an estimate of an estimate, so it is measured
 * here, against the SHIPPED estimator rather than a copy of it, and the run
 * that produced the recorded figure is named in `docs/ancestry-interval.md`.
 *
 *   node --import tsx scripts/ancestry-interval/measure.mts [seeds] [--json]
 *
 * Every draw is made up: a simulated person is assembled from the panel's own
 * reference frequencies at a chosen mixture. NOTHING HERE READS A REAL FILE,
 * and the measurement's ceiling is exactly that - the estimator is being
 * tested against data generated by its own assumption, so the coverage it
 * returns is an upper bound on what a real person gets. The surface says so
 * beside the figure (`RANGE_TEST_LIMIT`).
 */
import { AIMS, POPS, estimateAdmixture, type Pop } from "@/lib/genome/admixture";

/** mulberry32, so a run is reproducible from its seed alone. */
function random(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** One made-up person at a chosen mixture, as a genotype lookup over the panel. */
function simulated(seed: number, mixture: Partial<Record<Pop, number>>) {
  const rnd = random(seed);
  const weights = { AFR: 0, AMR: 0, EAS: 0, EUR: 0, SAS: 0, ...mixture } as Record<Pop, number>;
  const byPosition = new Map<string, string>();
  for (const marker of AIMS) {
    const alleles: string[] = [];
    for (let copy = 0; copy < 2; copy++) {
      let u = rnd();
      let pop: Pop = POPS[POPS.length - 1];
      for (const candidate of POPS) {
        u -= weights[candidate];
        if (u < 0) { pop = candidate; break; }
      }
      alleles.push(rnd() < marker.freqs[pop] ? marker.alt : marker.ref);
    }
    byPosition.set(`${marker.chrom}:${marker.pos38}`, alleles.join("/"));
  }
  return (chrom: number, pos: number) => byPosition.get(`${chrom}:${pos}`) ?? null;
}

/**
 * The mixtures. Single populations, then every pair at five splits, then three
 * three-way mixes: the small-component cases are the ones that stress an
 * interval, so they are in rather than a convenient middle.
 */
const PAIRS: Array<[Pop, Pop]> = [
  ["EUR", "AFR"], ["EUR", "EAS"], ["EUR", "SAS"], ["AFR", "EAS"],
  ["SAS", "EAS"], ["AMR", "EUR"], ["AFR", "SAS"], ["AMR", "AFR"],
];
const SPLITS = [0.05, 0.1, 0.2, 0.35, 0.5];
const MIXTURES: Array<Partial<Record<Pop, number>>> = [
  ...POPS.map((pop) => ({ [pop]: 1 }) as Partial<Record<Pop, number>>),
  ...PAIRS.flatMap(([a, b]) => SPLITS.map((split) => ({ [a]: 1 - split, [b]: split }) as Partial<Record<Pop, number>>)),
  { EUR: 0.6, AFR: 0.3, EAS: 0.1 },
  { AFR: 0.4, EUR: 0.35, SAS: 0.25 },
  { EUR: 0.5, EAS: 0.3, AMR: 0.2 },
];

/**
 * Banded by the POINT ESTIMATE, not by the truth, because that is the
 * conditioning a reader lives under: they see a share and want to know how
 * often the range around THAT contains the real number. Banding by the truth
 * answers a question nobody can ask at run time.
 */
const BANDS: Array<[string, (share: number) => boolean]> = [
  ["0", (v) => v === 0],
  ["0 to 5%", (v) => v > 0 && v <= 0.05],
  ["5 to 15%", (v) => v > 0.05 && v <= 0.15],
  ["15 to 35%", (v) => v > 0.15 && v <= 0.35],
  ["35 to 70%", (v) => v > 0.35 && v <= 0.7],
  ["70 to 100%", (v) => v > 0.7],
];

const seeds = Number(process.argv.find((arg) => /^\d+$/.test(arg)) ?? 60);
const asJson = process.argv.includes("--json");
const tally = BANDS.map(() => ({ held: 0, count: 0, width: 0, error: 0 }));

for (const [index, mixture] of MIXTURES.entries()) {
  const truth = { AFR: 0, AMR: 0, EAS: 0, EUR: 0, SAS: 0, ...mixture } as Record<Pop, number>;
  for (let seed = 1; seed <= seeds; seed++) {
    const result = estimateAdmixture(simulated(seed * 1013 + 7 + index * 1_000_003, mixture));
    for (const pop of POPS) {
      const share = result.proportions[pop];
      const range = result.ranges?.[pop] ?? { low: share, high: share };
      const band = tally[BANDS.findIndex(([, holds]) => holds(share))];
      band.count++;
      band.width += range.high - range.low;
      band.error += Math.abs(share - truth[pop]);
      if (range.low <= truth[pop] && truth[pop] <= range.high) band.held++;
    }
  }
}

const rows = BANDS.map(([label], index) => {
  const band = tally[index];
  return {
    share: label,
    estimates: band.count,
    coverage: band.count ? band.held / band.count : 0,
    meanWidth: band.count ? band.width / band.count : 0,
    meanPointError: band.count ? band.error / band.count : 0,
  };
});
const total = tally.reduce((sum, band) => ({
  held: sum.held + band.held, count: sum.count + band.count, width: sum.width + band.width,
}), { held: 0, count: 0, width: 0 });
const summary = {
  markers: AIMS.length, mixtures: MIXTURES.length, seeds,
  estimates: total.count,
  coverage: total.held / total.count,
  meanWidth: total.width / total.count,
  rows,
};

if (asJson) {
  process.stdout.write(`${JSON.stringify(summary, null, 2)}\n`);
} else {
  const pct = (value: number) => `${(100 * value).toFixed(1)}%`;
  console.log(`${summary.mixtures} mixtures x ${seeds} draws over ${summary.markers} markers`);
  console.log(`${summary.estimates} region-estimates\n`);
  console.log("share shown        estimates   range held it   mean width   mean |share - truth|");
  for (const row of rows) {
    console.log(`${row.share.padEnd(18)}${String(row.estimates).padStart(9)}${pct(row.coverage).padStart(15)}`
      + `${row.meanWidth.toFixed(3).padStart(13)}${row.meanPointError.toFixed(3).padStart(23)}`);
  }
  console.log(`\noverall            ${String(summary.estimates).padStart(9)}${pct(summary.coverage).padStart(15)}${summary.meanWidth.toFixed(3).padStart(13)}`);
}
