import { createReadStream } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { parseArray, type ArrayKind } from "./array";
import { toLines } from "./lines";

const fixture = (name: string) =>
  fileURLToPath(new URL(`./fixtures/${name}`, import.meta.url));

async function* fromString(text: string): AsyncIterable<string> {
  for (const line of text.split("\n")) yield line;
}

const parseFixture = (name: string, kind: ArrayKind) =>
  parseArray(toLines(createReadStream(fixture(name))), kind);

describe("parseArray: 23andMe", () => {
  it("parses the fixture", async () => {
    const result = await parseFixture("23andme.txt", "array_23andme");
    expect(result.build).toBe("GRCh37");
    // skipped: "--" no-call + "DI" indel pseudo-genotype
    expect(result.skipped).toBe(2);
    expect(result.records).toEqual([
      { rsid: 4477212, chrom: 1, pos: 82154, ref: null, alt: null, genotype: "A/A" },
      { rsid: 762551, chrom: 15, pos: 75041917, ref: null, alt: null, genotype: "A/C" },
      { rsid: 11575897, chrom: 24, pos: 2655180, ref: null, alt: null, genotype: "A" },
      { rsid: null, chrom: 25, pos: 16518, ref: null, alt: null, genotype: "G" },
    ]);
  });

  it("detects build 38 from header comments", async () => {
    const text =
      "# This data file generated by 23andMe\n# build 38 reference\nrs1\t1\t100\tAA\n";
    const result = await parseArray(fromString(text), "array_23andme");
    expect(result.build).toBe("GRCh38");
  });

  it.each(["# build 36", "# build 380", "# hg18", "# GRCh37\n# GRCh38", "# build 38\n# build 37"])("withholds unsupported/conflicting explicit builds: %s", async (header) => {
    expect((await parseArray(fromString(header + "\nrs1\t1\t100\tAA"), "array_23andme")).build).toBe("unknown");
  });
});

describe("parseArray: AncestryDNA", () => {
  it("parses the fixture (joined alleles, chrom remapping)", async () => {
    const result = await parseFixture("ancestry.txt", "array_ancestry");
    expect(result.build).toBe("GRCh37");
    expect(result.skipped).toBe(1); // "0 0" no-call
    expect(result.records).toEqual([
      { rsid: 4477212, chrom: 1, pos: 82154, ref: null, alt: null, genotype: "A/A" },
      { rsid: 762551, chrom: 15, pos: 75041917, ref: null, alt: null, genotype: "A/C" },
      // 24 = Y, homozygous -> haploid
      { rsid: 11575897, chrom: 24, pos: 2655180, ref: null, alt: null, genotype: "G" },
      // 26 = MT -> our 25, haploid
      { rsid: 199838004, chrom: 25, pos: 16518, ref: null, alt: null, genotype: "T" },
      // 25 = PAR -> X (23), stays diploid
      { rsid: 2032658, chrom: 23, pos: 1234567, ref: null, alt: null, genotype: "A/G" },
      { rsid: 4030303, chrom: 23, pos: 710265, ref: null, alt: null, genotype: "A/A" },
    ]);
  });
});

describe("parseArray: MyHeritage", () => {
  it("parses the quoted-CSV fixture", async () => {
    const result = await parseFixture("myheritage.csv", "array_myheritage");
    expect(result.build).toBe("GRCh37");
    expect(result.skipped).toBe(1); // "--"
    expect(result.records).toEqual([
      { rsid: 4477212, chrom: 1, pos: 82154, ref: null, alt: null, genotype: "A/A" },
      { rsid: 762551, chrom: 15, pos: 75041917, ref: null, alt: null, genotype: "A/C" },
      { rsid: 11575897, chrom: 24, pos: 2655180, ref: null, alt: null, genotype: "G" },
    ]);
  });
});

describe("parseArray: FamilyTreeDNA", () => {
  it("parses the unquoted-CSV fixture", async () => {
    const result = await parseFixture("ftdna.csv", "array_ftdna");
    expect(result.build).toBe("GRCh37");
    expect(result.skipped).toBe(1); // "--"
    expect(result.records).toEqual([
      { rsid: 4477212, chrom: 1, pos: 82154, ref: null, alt: null, genotype: "A/A" },
      { rsid: 762551, chrom: 15, pos: 75041917, ref: null, alt: null, genotype: "A/C" },
      { rsid: 22222, chrom: 25, pos: 16518, ref: null, alt: null, genotype: "T" },
    ]);
  });
});

describe("parseArray: genotype normalization and skips", () => {
  const line23 = (genotype: string, chrom = "1") =>
    `rs1\t${chrom}\t100\t${genotype}\n`;

  it("sorts diploid genotypes", async () => {
    const r = await parseArray(fromString(line23("TG")), "array_23andme");
    expect(r.records[0].genotype).toBe("G/T");
  });

  it("keeps heterozygous pairs on MT diploid but collapses homozygous", async () => {
    const het = await parseArray(fromString(line23("AG", "MT")), "array_23andme");
    expect(het.records[0].genotype).toBe("A/G");
    const hom = await parseArray(fromString(line23("AA", "MT")), "array_23andme");
    expect(hom.records[0].genotype).toBe("A");
  });

  it("counts 00, DD, II and junk genotypes as skipped", async () => {
    const text =
      line23("00") + line23("DD") + line23("II") + line23("ZQ") + line23("AC");
    const r = await parseArray(fromString(text), "array_23andme");
    expect(r.skipped).toBe(4);
    expect(r.records).toHaveLength(1);
  });

  it("skips unknown chroms and bad positions", async () => {
    const text = "rs1\tUn\t100\tAA\nrs2\t1\tabc\tAA\nrs3\t1\t\tAA\n";
    const r = await parseArray(fromString(text), "array_23andme");
    expect(r.skipped).toBe(3);
    expect(r.records).toHaveLength(0);
  });

  it("skips short lines as unparseable", async () => {
    const r = await parseArray(fromString("rs1\t1\t100\n"), "array_23andme");
    expect(r.skipped).toBe(1);
  });
});
