// Format detection from the first bytes of an uploaded raw genome file.

import { gunzipSync, constants as zlibConstants } from "node:zlib";
import type { FileKind } from "../types";

export interface SniffResult {
  kind: FileKind | null;
  compressed: boolean;
}

function startsWithBytes(buf: Uint8Array, magic: number[]): boolean {
  return magic.every((b, i) => buf[i] === b);
}

/**
 * Detect the file format from the first bytes of a file (a few KB is enough).
 * Handles gzip/bgzf-compressed input by decompressing what it can of the
 * leading member before inspecting the content. Node-only (zlib); browsers
 * use sniffFile from ./sniff-browser, which shares sniffHead below.
 */
export function sniff(bytes: Uint8Array): SniffResult {
  const compressed =
    bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b;

  let head = bytes;
  if (compressed) {
    try {
      // Z_SYNC_FLUSH tolerates a truncated trailing member, returning
      // whatever decompressed so far.
      head = gunzipSync(bytes, {
        finishFlush: zlibConstants.Z_SYNC_FLUSH,
      });
    } catch {
      return { kind: null, compressed };
    }
  }

  return sniffHead(head, compressed);
}

/** Pure content detection on an already-decompressed head. Runtime-agnostic. */
export function sniffHead(head: Uint8Array, compressed: boolean): SniffResult {
  // Binary magics: BAM ("BAM\1", inside bgzf) and CRAM ("CRAM", uncompressed).
  if (startsWithBytes(head, [0x42, 0x41, 0x4d, 0x01]))
    return { kind: "bam", compressed };
  if (startsWithBytes(head, [0x43, 0x52, 0x41, 0x4d]))
    return { kind: "cram", compressed };

  const text = new TextDecoder().decode(head.subarray(0, 65536));
  const lines = text.split(/\r?\n/);
  const first = lines[0] ?? "";

  if (first.startsWith("##fileformat=VCF")) {
    return { kind: text.includes("<NON_REF>") ? "gvcf" : "vcf", compressed };
  }
  if (first.startsWith("# This data file generated by 23andMe"))
    return { kind: "array_23andme", compressed };
  if (first.startsWith("#AncestryDNA"))
    return { kind: "array_ancestry", compressed };
  if (first.startsWith("##fileformat=MyHeritage"))
    return { kind: "array_myheritage", compressed };

  // Header-comment-less CSVs: distinguish MyHeritage (quoted) from
  // FamilyTreeDNA (unquoted) by the column-header row.
  const firstData = lines.find((l) => l !== "" && !l.startsWith("#"));
  if (firstData === '"RSID","CHROMOSOME","POSITION","RESULT"')
    return { kind: "array_myheritage", compressed };
  if (firstData === "RSID,CHROMOSOME,POSITION,RESULT")
    return { kind: "array_ftdna", compressed };

  return { kind: null, compressed };
}
