-- Reviewed carrier assertions (docs/carrier-importer-design.md; owner decisions
-- of 28 September 2026, docs/protocol/decisions.md).
--
-- Until now the carrier-pair reader returned nothing by construction: the
-- legacy `ref_variants` table is keyed by rsID, carries one ALT per rsID and
-- no condition, review status or release, so none of its labels could be
-- trusted with a personal result. This migration adds the tables that can
-- hold a reviewed assertion and the one rule that reads them:
--
--   - `clinical_assertion_releases`: one pinned source release (ClinVar's
--     monthly release, or a synthetic test release), with the SHA-256 of the
--     file it was read from and of ClinGen's gene-disease snapshot. At most
--     one current release per source; importing a new one retires the old.
--   - `carrier_conditions`: one condition per gene, keyed by MONDO id, with
--     its inheritance mode (not null, checked), ClinGen's gene-disease
--     classification, a penetrance class and a severity class. Written
--     INACTIVE by the importer; only a named reviewer activates one.
--   - `carrier_condition_reviews`: the append-only record of each review.
--   - `clinical_assertions`: one row per classified allele and condition,
--     keyed by the exact GRCh38 allele (chromosome, position, REF, ALT; simple
--     and left-aligned), with ClinVar's GRCh37 placement of the same allele,
--     the other GRCh38 spellings of an insertion or deletion inside a repeat,
--     the classification, review status and stars, the conflict flag and the
--     date ClinVar last evaluated it.
--
-- The production rule (`private.carrier_assertion_rule_v1`) returns an
-- assertion only when ALL of these hold: pathogenic or likely pathogenic, two
-- review stars or more, no conflict, a current (not retired) release, an
-- active reviewed condition whose ClinGen link is Definitive or Strong, and a
-- gene that matches the condition's. Anything else is not covered, never "not
-- a carrier". Nothing reads `ref_variants` any more for a carrier result.
--
-- Two readers use the rule, both service-only: the legacy-file reader in the
-- application, and `public.family_portrait_carrier_calls_v1`, which reads each
-- Portrait person's CURRENT PREPARED SOURCE at the rule's loci only, under the
-- exact authority `family_portrait_source_readiness_v1` already proves.
--
-- Runs of homozygosity for a prepared source: the carrier rule needs each
-- file's runs measure, which the legacy processing route stores and the
-- prepared path never did. `public.record_own_normalization_runs_v1` lets the
-- normalization route store the measure it takes from the verified bytes,
-- once, after the source is published (D-030: measured at ingest, never
-- re-derived by a reader).
--
-- No person's data is written by this migration, and every condition it
-- could create starts inactive. The ClinVar import itself is a separate
-- guarded apply generated by `scripts/build-carrier-assertions.ts --emit-sql`.

-- ---------------------------------------------------------------------------
-- Allele keys
-- ---------------------------------------------------------------------------

-- One definition of a keyable allele, shared with src/lib/family/allele-key.ts:
-- a single-letter change, or an insertion or deletion that shares exactly its
-- first letter with the other spelling and cannot move one base left (its
-- anchor differs from the last letter it adds or removes).
create function private.carrier_allele_key_valid_v1(p_ref text,p_alt text)
returns boolean language sql immutable set search_path='' as $$
 select coalesce(p_ref ~ '^[ACGT]+$' and p_alt ~ '^[ACGT]+$' and p_ref<>p_alt and (
  (length(p_ref)=1 and length(p_alt)=1)
  or (length(p_alt)=1 and length(p_ref)>1 and left(p_ref,1)=p_alt and right(p_ref,1)<>p_alt)
  or (length(p_ref)=1 and length(p_alt)>1 and left(p_alt,1)=p_ref and right(p_alt,1)<>p_ref)),false)
$$;

-- The other spellings of one left-aligned insertion or deletion: each a
-- [position, REF, ALT] triple to the right of the key, strictly increasing,
-- the same shape and lengths. A single-letter change has none.
create function private.carrier_equivalents_valid_v1(p_equivalents jsonb,p_pos integer,p_ref text,p_alt text)
returns boolean language plpgsql immutable set search_path='' as $$
declare e jsonb; previous integer:=p_pos;
begin
 if jsonb_typeof(p_equivalents) is distinct from 'array' then return false; end if;
 if length(p_ref)=1 and length(p_alt)=1 then return p_equivalents='[]'::jsonb; end if;
 if jsonb_array_length(p_equivalents)>64 then return false; end if;
 for e in select value from jsonb_array_elements(p_equivalents) loop
  if jsonb_typeof(e) is distinct from 'array' or jsonb_array_length(e)<>3
   or jsonb_typeof(e->0)<>'number' or jsonb_typeof(e->1)<>'string' or jsonb_typeof(e->2)<>'string'
   or (e->>0)!~'^[1-9][0-9]{0,9}$' or (e->>0)::bigint<=previous or (e->>0)::bigint>2147483647
   or (e->>1)!~'^[ACGT]+$' or (e->>2)!~'^[ACGT]+$'
   or length(e->>1)<>length(p_ref) or length(e->>2)<>length(p_alt)
   or left(e->>1,1)<>left(e->>2,1) then return false; end if;
  previous:=(e->>0)::integer;
 end loop;
 return true;
end; $$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.clinical_assertion_releases (
 release_id text primary key
  check (release_id ~ '^(clinvar-[0-9]{4}-(0[1-9]|1[0-2])|synthetic-[a-z0-9][a-z0-9-]{0,47})$'),
 source text not null check (source in ('clinvar','synthetic')),
 source_url text not null check (source_url ~ '^https://[^[:space:]]+$' and length(source_url)<=500),
 source_sha256 text not null check (source_sha256 ~ '^[0-9a-f]{64}$'),
 source_bytes bigint not null check (source_bytes>0),
 source_published_on date not null,
 retrieved_at timestamptz not null,
 extract_sha256 text not null check (extract_sha256 ~ '^[0-9a-f]{64}$'),
 gene_validity_url text not null check (gene_validity_url ~ '^https://[^[:space:]]+$' and length(gene_validity_url)<=500),
 gene_validity_sha256 text not null check (gene_validity_sha256 ~ '^[0-9a-f]{64}$'),
 gene_validity_created_on date not null,
 imported_at timestamptz not null default clock_timestamp(),
 retired_at timestamptz,
 check ((source='clinvar')=(release_id like 'clinvar-%')),
 check (retired_at is null or retired_at>=imported_at)
);
-- One current release per source: a new import retires the previous one.
create unique index clinical_assertion_releases_one_current
 on public.clinical_assertion_releases (source) where retired_at is null;

create table public.carrier_conditions (
 condition_id text primary key check (condition_id ~ '^(MONDO:[0-9]{7}|SYNTHETIC:[0-9]{1,7})$'),
 condition_name text not null check (condition_name=btrim(condition_name) and length(condition_name) between 1 and 80),
 gene_symbol text not null check (gene_symbol ~ '^[A-Z0-9][A-Z0-9-]{0,19}$'),
 -- X16.3: stored, not null, and one of five values. Where it is unknown,
 -- other or dominant the carrier rule refuses the arithmetic by name.
 inheritance_mode text not null
  check (inheritance_mode in ('autosomal_recessive','autosomal_dominant','x_linked','other','unknown')),
 gene_validity_classification text not null check (gene_validity_classification in
  ('Definitive','Strong','Moderate','Limited','Disputed','Refuted','No Known Disease Relationship')),
 gene_validity_classified_on date not null,
 gene_validity_url text not null check (gene_validity_url ~ '^https://[^[:space:]]+$' and length(gene_validity_url)<=500),
 -- Brief line 1332: a cited range, or "not established". Nothing is cited yet.
 penetrance_class text not null default 'unestablished'
  check (penetrance_class in ('high','moderate','low','unestablished')),
 penetrance_citation text check (penetrance_citation is null or length(penetrance_citation) between 3 and 300),
 -- ADR 0034 needs a serious-condition judgement; only a reviewer gives one.
 severity_class text not null default 'unreviewed' check (severity_class in ('serious','not_serious','unreviewed')),
 synthetic boolean not null default false,
 registry_revision bigint not null default 1 check (registry_revision>0),
 active boolean not null default false,
 active_review_id bigint,
 check ((penetrance_class='unestablished')=(penetrance_citation is null)),
 check (synthetic=(condition_id like 'SYNTHETIC:%')),
 check (active=(active_review_id is not null)),
 check (not active or severity_class<>'unreviewed'),
 unique (condition_id,gene_symbol)
);
-- The carrier rule answers per gene, so a gene names at most one condition.
create unique index carrier_conditions_one_per_gene on public.carrier_conditions (gene_symbol);

create table public.carrier_condition_reviews (
 review_id bigint generated always as identity primary key,
 condition_id text not null references public.carrier_conditions(condition_id) on delete restrict,
 registry_revision bigint not null check (registry_revision>0),
 decision text not null check (decision in ('activate','deactivate')),
 reviewer_name text not null check (reviewer_name=btrim(reviewer_name) and length(reviewer_name) between 3 and 120),
 reviewer_role text not null check (reviewer_role=btrim(reviewer_role) and length(reviewer_role) between 3 and 160),
 review_reference text not null check (review_reference=btrim(review_reference) and length(review_reference) between 3 and 500),
 severity_class text check (severity_class in ('serious','not_serious')),
 decided_at timestamptz not null default clock_timestamp(),
 check ((decision='activate')=(severity_class is not null))
);
alter table public.carrier_conditions add constraint carrier_conditions_active_review_fkey
 foreign key (active_review_id) references public.carrier_condition_reviews(review_id) on delete restrict;

create table public.clinical_assertions (
 assertion_id bigint generated always as identity primary key,
 release_id text not null references public.clinical_assertion_releases(release_id) on delete restrict,
 variation_id bigint not null check (variation_id>0),
 condition_id text not null,
 gene_symbol text not null,
 variant_name text not null check (length(variant_name) between 1 and 500),
 classification text not null check (classification in ('Pathogenic','Likely pathogenic','Pathogenic/Likely pathogenic',
  'Uncertain significance','Likely benign','Benign','Benign/Likely benign','Conflicting classifications of pathogenicity')),
 review_status text not null check (review_status in ('practice guideline','reviewed by expert panel',
  'criteria provided, multiple submitters, no conflicts','criteria provided, conflicting classifications',
  'criteria provided, single submitter','no assertion criteria provided','no classification provided')),
 review_stars smallint not null,
 conflict boolean not null,
 last_evaluated date,
 grch38_chrom smallint not null check (grch38_chrom between 1 and 22),
 grch38_pos integer not null check (grch38_pos>0),
 grch38_ref text not null,
 grch38_alt text not null,
 grch37_chrom smallint check (grch37_chrom between 1 and 22),
 grch37_pos integer check (grch37_pos>0),
 grch37_ref text,
 grch37_alt text,
 grch38_equivalents jsonb not null default '[]'::jsonb,
 foreign key (condition_id,gene_symbol) references public.carrier_conditions(condition_id,gene_symbol) on delete restrict,
 -- ClinVar's own table of stars (https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/).
 check (review_stars=case review_status when 'practice guideline' then 4 when 'reviewed by expert panel' then 3
  when 'criteria provided, multiple submitters, no conflicts' then 2 when 'criteria provided, single submitter' then 1
  when 'criteria provided, conflicting classifications' then 1 else 0 end),
 check (conflict or (review_status<>'criteria provided, conflicting classifications'
  and classification<>'Conflicting classifications of pathogenicity')),
 check (private.carrier_allele_key_valid_v1(grch38_ref,grch38_alt)),
 check ((grch37_chrom is null)=(grch37_pos is null) and (grch37_chrom is null)=(grch37_ref is null)
  and (grch37_chrom is null)=(grch37_alt is null)),
 check (grch37_ref is null or (grch37_chrom=grch38_chrom and private.carrier_allele_key_valid_v1(grch37_ref,grch37_alt)
  and length(grch37_ref)=length(grch38_ref) and length(grch37_alt)=length(grch38_alt))),
 check (private.carrier_equivalents_valid_v1(grch38_equivalents,grch38_pos,grch38_ref,grch38_alt)),
 unique (release_id,variation_id,condition_id),
 unique (release_id,grch38_chrom,grch38_pos,grch38_ref,grch38_alt)
);
create index clinical_assertions_condition_idx on public.clinical_assertions (condition_id,release_id);

alter table public.clinical_assertion_releases enable row level security;
alter table public.carrier_conditions enable row level security;
alter table public.carrier_condition_reviews enable row level security;
alter table public.clinical_assertions enable row level security;
revoke all on table public.clinical_assertion_releases,public.carrier_conditions,
 public.carrier_condition_reviews,public.clinical_assertions from public,anon,authenticated,inherit_upload_only;
-- Service reads only; every write goes through the doors below.
revoke all on table public.clinical_assertion_releases,public.carrier_conditions,
 public.carrier_condition_reviews,public.clinical_assertions from service_role;
grant select on table public.clinical_assertion_releases,public.carrier_conditions,
 public.carrier_condition_reviews,public.clinical_assertions to service_role;

-- A condition is active only through a recorded activation of its current
-- revision; any other change to what was reviewed deactivates it.
create function private.guard_carrier_condition_v1()
returns trigger language plpgsql security definer set search_path=pg_catalog as $$
declare r public.carrier_condition_reviews%rowtype;
begin
 if tg_op='UPDATE' and (new.condition_id,new.gene_symbol,new.synthetic) is distinct from
  (old.condition_id,old.gene_symbol,old.synthetic) then
  raise exception using errcode='55000',message='carrier_condition_identity_immutable'; end if;
 if new.active then
  select * into r from public.carrier_condition_reviews where review_id=new.active_review_id;
  if r.review_id is null or r.condition_id<>new.condition_id or r.decision<>'activate'
   or r.registry_revision<>new.registry_revision or r.severity_class is distinct from new.severity_class then
   raise exception using errcode='42501',message='carrier_condition_review_required'; end if;
 end if;
 return new;
end; $$;
revoke all on function private.guard_carrier_condition_v1() from public,anon,authenticated,inherit_upload_only,service_role;
create trigger carrier_conditions_reviewed before insert or update on public.carrier_conditions
 for each row execute function private.guard_carrier_condition_v1();

-- ---------------------------------------------------------------------------
-- The rule
-- ---------------------------------------------------------------------------

create function private.carrier_assertion_rule_v1()
returns table(assertion_id bigint,release_id text,variation_id bigint,condition_id text,condition_name text,
 gene_symbol text,inheritance_mode text,penetrance_class text,penetrance_citation text,variant_name text,
 classification text,review_status text,review_stars smallint,last_evaluated date,
 chrom smallint,pos integer,ref text,alt text,equivalents jsonb)
language sql stable security definer set search_path=pg_catalog as $$
 select a.assertion_id,a.release_id,a.variation_id,c.condition_id,c.condition_name,c.gene_symbol,c.inheritance_mode,
  c.penetrance_class,c.penetrance_citation,a.variant_name,a.classification,a.review_status,a.review_stars,a.last_evaluated,
  a.grch38_chrom,a.grch38_pos,a.grch38_ref,a.grch38_alt,a.grch38_equivalents
 from public.clinical_assertions a
 join public.clinical_assertion_releases r on r.release_id=a.release_id
 join public.carrier_conditions c on c.condition_id=a.condition_id and c.gene_symbol=a.gene_symbol
 where r.retired_at is null
  and c.active and c.gene_validity_classification in ('Definitive','Strong')
  and c.synthetic=(r.source='synthetic')
  and a.classification in ('Pathogenic','Likely pathogenic','Pathogenic/Likely pathogenic')
  and a.review_stars>=2 and not a.conflict
 order by c.gene_symbol,a.grch38_pos,a.assertion_id
$$;
revoke all on function private.carrier_assertion_rule_v1() from public,anon,authenticated,inherit_upload_only,service_role;

-- The rule's rows for the application's legacy-file reader, and nothing else.
create function public.carrier_assertions_v1()
returns jsonb language sql stable security definer set search_path=pg_catalog as $$
 select coalesce(jsonb_agg(to_jsonb(r) order by r.gene_symbol,r.pos,r.assertion_id),'[]'::jsonb)
 from private.carrier_assertion_rule_v1() r
$$;

-- ---------------------------------------------------------------------------
-- The import door (service only): inactive conditions, one release
-- ---------------------------------------------------------------------------

create function public.import_clinical_assertion_release_v1(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare rel jsonb; c jsonb; a jsonb; existing public.carrier_conditions%rowtype; v_source text; v_release text;
 v_retired text[]; v_assertions integer:=0; v_conditions integer:=0; v_synthetic boolean;
begin
 if jsonb_typeof(p_payload) is distinct from 'object' or not (p_payload ?& array['release','conditions','assertions'])
  or p_payload-array['release','conditions','assertions']<>'{}'::jsonb
  or jsonb_typeof(p_payload->'conditions') is distinct from 'array'
  or jsonb_typeof(p_payload->'assertions') is distinct from 'array'
  or jsonb_array_length(p_payload->'conditions') not between 1 and 50
  or jsonb_array_length(p_payload->'assertions') not between 1 and 100000 then
  raise exception using errcode='22023',message='invalid_request'; end if;
 rel:=p_payload->'release';
 if jsonb_typeof(rel) is distinct from 'object' or not (rel ?& array['releaseId','source','sourceUrl','sourceSha256',
  'sourceBytes','sourcePublishedOn','retrievedAt','extractSha256','geneValidityUrl','geneValiditySha256','geneValidityCreatedOn'])
  or rel-array['releaseId','source','sourceUrl','sourceSha256','sourceBytes','sourcePublishedOn','retrievedAt',
   'extractSha256','geneValidityUrl','geneValiditySha256','geneValidityCreatedOn']<>'{}'::jsonb then
  raise exception using errcode='22023',message='invalid_request'; end if;
 v_source:=rel->>'source'; v_release:=rel->>'releaseId'; v_synthetic:=v_source='synthetic';
 perform 1 from public.clinical_assertion_releases where source=v_source for update;
 with retired as (update public.clinical_assertion_releases set retired_at=clock_timestamp()
  where source=v_source and retired_at is null returning release_id)
 select coalesce(array_agg(release_id order by release_id),'{}') into v_retired from retired;
 insert into public.clinical_assertion_releases(release_id,source,source_url,source_sha256,source_bytes,source_published_on,
  retrieved_at,extract_sha256,gene_validity_url,gene_validity_sha256,gene_validity_created_on)
 values(v_release,v_source,rel->>'sourceUrl',rel->>'sourceSha256',(rel->>'sourceBytes')::bigint,
  (rel->>'sourcePublishedOn')::date,(rel->>'retrievedAt')::timestamptz,rel->>'extractSha256',rel->>'geneValidityUrl',
  rel->>'geneValiditySha256',(rel->>'geneValidityCreatedOn')::date);
 for c in select value from jsonb_array_elements(p_payload->'conditions') loop
  if jsonb_typeof(c) is distinct from 'object' or not (c ?& array['conditionId','conditionName','geneSymbol','inheritanceMode',
   'geneValidityClassification','geneValidityClassifiedOn','geneValidityUrl'])
   or c-array['conditionId','conditionName','geneSymbol','inheritanceMode','geneValidityClassification',
    'geneValidityClassifiedOn','geneValidityUrl']<>'{}'::jsonb
   or ((c->>'conditionId') like 'SYNTHETIC:%') is distinct from v_synthetic then
   raise exception using errcode='22023',message='invalid_request'; end if;
  select * into existing from public.carrier_conditions where condition_id=c->>'conditionId' for update;
  if existing.condition_id is null then
   insert into public.carrier_conditions(condition_id,condition_name,gene_symbol,inheritance_mode,gene_validity_classification,
    gene_validity_classified_on,gene_validity_url,synthetic)
   values(c->>'conditionId',c->>'conditionName',c->>'geneSymbol',c->>'inheritanceMode',c->>'geneValidityClassification',
    (c->>'geneValidityClassifiedOn')::date,c->>'geneValidityUrl',v_synthetic);
  elsif (existing.condition_name,existing.inheritance_mode,existing.gene_validity_classification,
   existing.gene_validity_classified_on,existing.gene_validity_url) is distinct from
   (c->>'conditionName',c->>'inheritanceMode',c->>'geneValidityClassification',
    (c->>'geneValidityClassifiedOn')::date,c->>'geneValidityUrl') then
   -- What a reviewer approved has changed: a new revision, inactive again.
   update public.carrier_conditions set condition_name=c->>'conditionName',inheritance_mode=c->>'inheritanceMode',
    gene_validity_classification=c->>'geneValidityClassification',
    gene_validity_classified_on=(c->>'geneValidityClassifiedOn')::date,gene_validity_url=c->>'geneValidityUrl',
    registry_revision=existing.registry_revision+1,active=false,active_review_id=null,severity_class='unreviewed'
   where condition_id=existing.condition_id and gene_symbol=c->>'geneSymbol';
   if not found then raise exception using errcode='22023',message='invalid_request'; end if;
  elsif existing.gene_symbol<>c->>'geneSymbol' then raise exception using errcode='22023',message='invalid_request';
  end if;
  v_conditions:=v_conditions+1;
 end loop;
 for a in select value from jsonb_array_elements(p_payload->'assertions') loop
  if jsonb_typeof(a) is distinct from 'object' or not (a ?& array['variationId','conditionId','geneSymbol','variantName',
   'classification','reviewStatus','reviewStars','conflict','lastEvaluated','grch38','grch37','grch38Equivalents'])
   or a-array['variationId','conditionId','geneSymbol','variantName','classification','reviewStatus','reviewStars',
    'conflict','lastEvaluated','grch38','grch37','grch38Equivalents']<>'{}'::jsonb
   or jsonb_typeof(a->'grch38') is distinct from 'array' or jsonb_array_length(a->'grch38')<>4
   or (jsonb_typeof(a->'grch37')<>'null' and (jsonb_typeof(a->'grch37')<>'array' or jsonb_array_length(a->'grch37')<>4))
   or jsonb_typeof(a->'conflict') is distinct from 'boolean'
   or not exists(select 1 from jsonb_array_elements(p_payload->'conditions') x where x->>'conditionId'=a->>'conditionId') then
   raise exception using errcode='22023',message='invalid_request'; end if;
  insert into public.clinical_assertions(release_id,variation_id,condition_id,gene_symbol,variant_name,classification,
   review_status,review_stars,conflict,last_evaluated,grch38_chrom,grch38_pos,grch38_ref,grch38_alt,
   grch37_chrom,grch37_pos,grch37_ref,grch37_alt,grch38_equivalents)
  values(v_release,(a->>'variationId')::bigint,a->>'conditionId',a->>'geneSymbol',a->>'variantName',a->>'classification',
   a->>'reviewStatus',(a->>'reviewStars')::smallint,(a->>'conflict')::boolean,(a->>'lastEvaluated')::date,
   (a#>>'{grch38,0}')::smallint,(a#>>'{grch38,1}')::integer,a#>>'{grch38,2}',a#>>'{grch38,3}',
   (a#>>'{grch37,0}')::smallint,(a#>>'{grch37,1}')::integer,a#>>'{grch37,2}',a#>>'{grch37,3}',a->'grch38Equivalents');
  v_assertions:=v_assertions+1;
 end loop;
 return jsonb_build_object('releaseId',v_release,'retired',to_jsonb(v_retired),'conditions',v_conditions,'assertions',v_assertions);
exception when invalid_text_representation or numeric_value_out_of_range or datetime_field_overflow
 or invalid_datetime_format or check_violation or not_null_violation or foreign_key_violation or unique_violation then
 raise exception using errcode='22023',message='invalid_request';
end; $$;

-- ---------------------------------------------------------------------------
-- The review door (service only): a named person activates or withdraws
-- ---------------------------------------------------------------------------

create function public.review_carrier_condition_v1(p_condition_id text,p_registry_revision bigint,p_decision text,
 p_reviewer_name text,p_reviewer_role text,p_review_reference text,p_severity_class text default null)
returns bigint language plpgsql security definer set search_path=pg_catalog as $$
declare c public.carrier_conditions%rowtype; v_review bigint;
begin
 select * into c from public.carrier_conditions where condition_id=p_condition_id for update;
 if c.condition_id is null or c.registry_revision is distinct from p_registry_revision
  or p_decision is null or p_decision not in ('activate','deactivate') then
  raise exception using errcode='22023',message='invalid_request'; end if;
 if p_decision='activate' and (c.gene_validity_classification not in ('Definitive','Strong')
  or p_severity_class is null or p_severity_class not in ('serious','not_serious')
  -- ADR 0034: a sex-linked condition only when a reviewer has judged it serious.
  or (c.inheritance_mode='x_linked' and p_severity_class<>'serious')) then
  raise exception using errcode='55000',message='carrier_condition_not_activatable'; end if;
 insert into public.carrier_condition_reviews(condition_id,registry_revision,decision,reviewer_name,reviewer_role,
  review_reference,severity_class)
 values(c.condition_id,c.registry_revision,p_decision,p_reviewer_name,p_reviewer_role,p_review_reference,
  case when p_decision='activate' then p_severity_class end)
 returning review_id into v_review;
 if p_decision='activate' then
  update public.carrier_conditions set active=true,active_review_id=v_review,severity_class=p_severity_class
  where condition_id=c.condition_id;
 else
  update public.carrier_conditions set active=false,active_review_id=null where condition_id=c.condition_id;
 end if;
 return v_review;
exception when check_violation or not_null_violation then
 raise exception using errcode='22023',message='invalid_request';
end; $$;

-- ---------------------------------------------------------------------------
-- Portrait: the carrier reader over each person's current prepared source
-- ---------------------------------------------------------------------------

create function private.family_portrait_carrier_side_v1(p_account uuid,p_subject uuid,p_loci jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare s jsonb; f public.genome_files%rowtype; v jsonb; o jsonb;
begin
 s:=private.family_portrait_prepared_source_v1(p_account,p_subject);
 if s->'source' is null or s->'source'='null'::jsonb then return null; end if;
 select * into f from public.genome_files where id=(s#>>'{source,fileId}')::uuid and subject_id=p_subject and user_id=p_account;
 if f.id is null or f.upload_revision::text is distinct from s#>>'{source,revision}' or f.sha256 is distinct from s#>>'{source,rawSha256}' then
  raise exception using errcode='42501',message='not_found'; end if;
 -- Only the rule's loci are read; the caller supplies none.
 select coalesce(jsonb_agg(jsonb_build_object('chrom',x.chrom,'pos',x.pos,'ref',x.ref,'alt',x.alt,'genotype',x.genotype)
  order by x.chrom,x.pos,x.id),'[]'::jsonb) into v
 from (select distinct uv.id,uv.chrom,uv.pos,uv.ref,uv.alt,uv.genotype
  from jsonb_to_recordset(p_loci) l(chrom smallint,pos integer)
  join public.user_variants uv on uv.subject_id=p_subject and uv.chrom=l.chrom and uv.pos=l.pos
  where uv.file_id=f.id and uv.user_id=p_account) x;
 select coalesce(jsonb_agg(jsonb_build_object('chrom',x.chrom,'pos',x.pos,'ref',x.ref,'alt',x.alt,'genotype',x.genotype,
  'usable',x.usable) order by x.chrom,x.pos,x.source_line),'[]'::jsonb) into o
 from (select distinct rc.source_line,rc.chrom,rc.pos,rc.ref,rc.alt,rc.genotype,rc.usable
  from jsonb_to_recordset(p_loci) l(chrom smallint,pos integer)
  join public.report_observed_calls rc on rc.file_id=f.id and rc.chrom=l.chrom and rc.pos=l.pos
  where rc.subject_id=p_subject and rc.user_id=p_account and rc.source_sha256=f.sha256
   and rc.extraction_version='vcf-literal-diploid-snp-v1' and rc.source_build=f.build) x;
 return jsonb_build_object('fileId',f.id,'runs',jsonb_build_object('status',f.roh_status,'reason',f.roh_reason,
  'totalBases',f.roh_total_bases,'coveredBases',f.roh_covered_bases,'fraction',f.roh_fraction),
  'variants',v,'observed',o);
end; $$;
revoke all on function private.family_portrait_carrier_side_v1(uuid,uuid,jsonb)
 from public,anon,authenticated,inherit_upload_only,service_role;

-- The page captures a readiness receipt first; this reader proves the same
-- receipt again (both current Portrait grants, sessions, acknowledgements,
-- independent logins and exact prepared sources, under the same locks) and
-- only then reads. It returns null on any difference, and for a pair whose
-- sources are not both canonical. The page's last await still re-confirms
-- the receipt before anything renders.
create function public.family_portrait_carrier_calls_v1(p_account_id uuid,p_session_id uuid,p_pair_id uuid,
 p_counterpart_account_id uuid,p_expected text)
returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare readiness jsonb; authority jsonb; rule jsonb; loci jsonb; sa jsonb; sb jsonb;
begin
 if p_expected is null or p_expected!~'^[0-9a-f]{64}$' then return null; end if;
 readiness:=public.family_portrait_source_readiness_v1(p_account_id,p_session_id,p_pair_id,p_counterpart_account_id,p_expected);
 if readiness is null or readiness->>'receipt' is distinct from p_expected or readiness->>'kind'<>'canonical' then return null; end if;
 authority:=private.family_portrait_authority_v1(p_account_id,p_session_id,p_pair_id,p_counterpart_account_id);
 if authority is null or (authority->>'strong')::boolean is not true
  or authority#>>'{subjectA,id}' is distinct from readiness#>>'{a,subjectId}'
  or authority#>>'{subjectB,id}' is distinct from readiness#>>'{b,subjectId}' then return null; end if;
 select coalesce(jsonb_agg(to_jsonb(r) order by r.gene_symbol,r.pos,r.assertion_id),'[]'::jsonb) into rule
 from private.carrier_assertion_rule_v1() r;
 select coalesce(jsonb_agg(distinct jsonb_build_object('chrom',l.chrom,'pos',l.pos)),'[]'::jsonb) into loci from (
  select (x->>'chrom')::smallint chrom,(x->>'pos')::integer pos from jsonb_array_elements(rule) x
  union select (x->>'chrom')::smallint,(e->>0)::integer from jsonb_array_elements(rule) x
   cross join lateral jsonb_array_elements(x->'equivalents') e) l;
 if jsonb_array_length(rule)>0 then
  if (readiness#>>'{a,hasPreparedSource}')::boolean then
   sa:=private.family_portrait_carrier_side_v1((authority#>>'{subjectA,accountId}')::uuid,(authority#>>'{subjectA,id}')::uuid,loci);
  end if;
  if (readiness#>>'{b,hasPreparedSource}')::boolean then
   sb:=private.family_portrait_carrier_side_v1((authority#>>'{subjectB,accountId}')::uuid,(authority#>>'{subjectB,id}')::uuid,loci);
  end if;
 end if;
 return jsonb_build_object('receipt',p_expected,'assertions',rule,
  'a',jsonb_build_object('subjectId',readiness#>>'{a,subjectId}','source',sa),
  'b',jsonb_build_object('subjectId',readiness#>>'{b,subjectId}','source',sb));
exception when lock_not_available or insufficient_privilege or object_not_in_prerequisite_state or invalid_text_representation then return null;
end; $$;

-- ---------------------------------------------------------------------------
-- Runs of homozygosity for a prepared source, measured at ingest
-- ---------------------------------------------------------------------------

create function public.record_own_normalization_runs_v1(p_account_id uuid,p_session_id uuid,p_file_id uuid,p_runs jsonb)
returns boolean language plpgsql security definer set search_path=pg_catalog,private as $$
declare f public.genome_files%rowtype;
begin
 if jsonb_typeof(p_runs) is distinct from 'object' or coalesce(p_runs->>'status','') not in ('measured','not_measurable')
  or (p_runs->>'status'='measured' and (not (p_runs ?& array['status','totalBases','coveredBases','fraction'])
   or p_runs-array['status','totalBases','coveredBases','fraction']<>'{}'::jsonb
   or jsonb_typeof(p_runs->'totalBases')<>'number' or jsonb_typeof(p_runs->'coveredBases')<>'number'
   or jsonb_typeof(p_runs->'fraction')<>'number'))
  or (p_runs->>'status'='not_measurable' and (not (p_runs ?& array['status','reason'])
   or p_runs-array['status','reason']<>'{}'::jsonb)) then
  raise exception using errcode='22023',message='invalid_request'; end if;
 select * into f from public.genome_files where id=p_file_id and user_id=p_account_id;
 if f.id is null or f.subject_id is null then raise exception using errcode='42501',message='not_found'; end if;
 -- The same live session, store consent and subject authority the upload used.
 perform private.own_upload_store_authority_v1(p_account_id,p_session_id,f.subject_id);
 select * into f from public.genome_files where id=p_file_id and user_id=p_account_id for update;
 if f.single_logical_sample_verified_at is null or f.structural_validator_version is distinct from 'single-logical-sample-v1'
  or f.normalization_completed_at is null or f.normalization_source_revision is distinct from f.upload_revision
  or not exists(select 1 from private.own_normalization_runs n where n.file_id=f.id and n.account_id=p_account_id and n.state='complete')
  or exists(select 1 from private.genome_file_deletions where file_id=f.id) then
  raise exception using errcode='42501',message='not_found'; end if;
 -- Measured once: a stored measure is never replaced.
 if f.roh_status is not null then return false; end if;
 update public.genome_files set
  roh_status=p_runs->>'status',
  roh_reason=case when p_runs->>'status'='not_measurable' then p_runs->>'reason' end,
  roh_total_bases=case when p_runs->>'status'='measured' then (p_runs->>'totalBases')::bigint end,
  roh_covered_bases=case when p_runs->>'status'='measured' then (p_runs->>'coveredBases')::bigint end,
  roh_fraction=case when p_runs->>'status'='measured' then round((p_runs->>'fraction')::numeric,6) end,
  roh_measured_at=clock_timestamp()
 where id=f.id;
 return true;
exception when check_violation or invalid_text_representation or numeric_value_out_of_range then
 raise exception using errcode='22023',message='invalid_request';
end; $$;

revoke all on function private.carrier_allele_key_valid_v1(text,text),
 private.carrier_equivalents_valid_v1(jsonb,integer,text,text) from public,anon,authenticated,inherit_upload_only;
revoke all on function public.carrier_assertions_v1(),public.import_clinical_assertion_release_v1(jsonb),
 public.review_carrier_condition_v1(text,bigint,text,text,text,text,text),
 public.family_portrait_carrier_calls_v1(uuid,uuid,uuid,uuid,text),
 public.record_own_normalization_runs_v1(uuid,uuid,uuid,jsonb) from public,anon,authenticated,inherit_upload_only;
grant execute on function public.carrier_assertions_v1(),public.import_clinical_assertion_release_v1(jsonb),
 public.review_carrier_condition_v1(text,bigint,text,text,text,text,text),
 public.family_portrait_carrier_calls_v1(uuid,uuid,uuid,uuid,text),
 public.record_own_normalization_runs_v1(uuid,uuid,uuid,jsonb) to service_role;
