import AdmZip from "adm-zip";
import register from "../../../docs/route-register.json";
import { describe, expect, it, vi } from "vitest";
import { hasZipMagic, MAXIMUM_LOCAL_ZIP_BYTES, openOwnUploadZip } from "./own-upload-zip";

const raw = Buffer.from("# This data file generated by 23andMe; invented calls\n# build 38\n# rsid\tchromosome\tposition\tgenotype\nrs762551\t15\t74749576\tAC\n");
function archive(content = raw) {
  const zip = new AdmZip();
  zip.addFile("private-person-name.txt", content);
  return zip.toBuffer();
}
const file = (bytes: Uint8Array) => new File([bytes as BlobPart], "private-archive-name.zip");
const central = (bytes: Buffer) => bytes.readUInt32LE(bytes.length - 6);

describe("bounded local single-file ZIP", () => {
  it("uses the registered local cap without importing the register into the browser bundle", () => {
    expect(MAXIMUM_LOCAL_ZIP_BYTES).toBe(register.payloadBoundaryContract.ownZipPreflightMaximumBytes);
  });
  it("returns exact raw bytes with no original name or archive metadata", async () => {
    const bytes = archive();
    expect(hasZipMagic(bytes)).toBe(true);
    const result = await openOwnUploadZip(file(bytes), raw.length);
    expect(Buffer.from(await result.arrayBuffer())).toEqual(raw);
    expect(result.name).toBe("raw-dna-data");
  });

  it("accepts a stored entry without deflating it", async () => {
    const zip = new AdmZip();
    zip.addFile("raw.txt", raw);
    zip.getEntry("raw.txt")!.header.method = 0;
    const bytes = zip.toBuffer();
    expect(bytes.readUInt16LE(8)).toBe(0);
    expect(Buffer.from(await (await openOwnUploadZip(file(bytes), raw.length)).arrayBuffer())).toEqual(raw);
  });

  it.each([false, true])("accepts a matching streamed data descriptor (signature %s)", async signed => {
    const bytes = archive(), at = central(bytes), descriptor = Buffer.alloc(signed ? 16 : 12);
    const start = signed ? 4 : 0;
    if (signed) descriptor.writeUInt32LE(0x08074b50, 0);
    descriptor.writeUInt32LE(bytes.readUInt32LE(at + 16), start);
    descriptor.writeUInt32LE(bytes.readUInt32LE(at + 20), start + 4);
    descriptor.writeUInt32LE(bytes.readUInt32LE(at + 24), start + 8);
    bytes.writeUInt16LE(bytes.readUInt16LE(6) | 8, 6);
    bytes.writeUInt16LE(bytes.readUInt16LE(at + 8) | 8, at + 8);
    bytes.fill(0, 14, 26);
    const streamed = Buffer.concat([bytes.subarray(0, at), descriptor, bytes.subarray(at)]);
    streamed.writeUInt32LE(at + descriptor.length, streamed.length - 6);
    expect(Buffer.from(await (await openOwnUploadZip(file(streamed), raw.length)).arrayBuffer())).toEqual(raw);
    streamed[at + start] ^= 1;
    await expect(openOwnUploadZip(file(streamed), raw.length)).rejects.toMatchObject({ code: "archive_invalid" });
  });

  it("refuses a declared one-byte-over expansion before reading compressed data", async () => {
    const source = file(archive()), stream = vi.spyOn(Blob.prototype, "stream");
    try {
      await expect(openOwnUploadZip(source, raw.length - 1)).rejects.toMatchObject({ code: "too_large", limitBytes: raw.length - 1 });
      expect(stream).not.toHaveBeenCalled();
    } finally { stream.mockRestore(); }
  });

  it("bounds the selected archive before reading its directory", async () => {
    const source = file(archive());
    Object.defineProperty(source, "size", { value: MAXIMUM_LOCAL_ZIP_BYTES + 1 });
    const slice = vi.spyOn(source, "slice");
    await expect(openOwnUploadZip(source, 2 * MAXIMUM_LOCAL_ZIP_BYTES)).rejects.toMatchObject({
      code: "too_large", limitBytes: MAXIMUM_LOCAL_ZIP_BYTES,
    });
    expect(slice).not.toHaveBeenCalled();
  });

  it("does not trust matching false small sizes or CRC values", async () => {
    const small = archive();
    small.writeUInt32LE(1, 22); small.writeUInt32LE(1, central(small) + 24);
    await expect(openOwnUploadZip(file(small), raw.length)).rejects.toMatchObject({ code: "archive_invalid" });
    await expect(openOwnUploadZip(file(small), 2)).rejects.toMatchObject({ code: "too_large", limitBytes: 2 });
    const crc = archive();
    crc.writeUInt32LE(0, 14); crc.writeUInt32LE(0, central(crc) + 16);
    await expect(openOwnUploadZip(file(crc), raw.length)).rejects.toMatchObject({ code: "archive_invalid" });
  });

  it("refuses multiple files instead of guessing which person's DNA to use", async () => {
    const zip = new AdmZip(); zip.addFile("one.txt", raw); zip.addFile("two.txt", raw);
    await expect(openOwnUploadZip(file(zip.toBuffer()), 1000)).rejects.toMatchObject({ code: "archive_invalid" });
  });

  it.each([
    ["encryption", (bytes: Buffer) => { bytes.writeUInt16LE(1, 6); bytes.writeUInt16LE(1, central(bytes) + 8); }],
    ["unsupported method", (bytes: Buffer) => { bytes.writeUInt16LE(9, 8); bytes.writeUInt16LE(9, central(bytes) + 10); }],
    ["symlink", (bytes: Buffer) => { bytes.writeUInt32LE(0xa1ff0000, central(bytes) + 38); }],
    ["directory", (bytes: Buffer) => { bytes.writeUInt32LE(0x10, central(bytes) + 38); }],
    ["local filename mismatch", (bytes: Buffer) => { bytes[30] ^= 1; }],
    ["local CRC mismatch", (bytes: Buffer) => { bytes[14] ^= 1; }],
    ["split archive", (bytes: Buffer) => { bytes.writeUInt16LE(1, bytes.length - 18); }],
    ["ZIP64 sentinel", (bytes: Buffer) => { bytes.writeUInt32LE(0xffffffff, central(bytes) + 20); }],
    ["hidden first entry", (bytes: Buffer) => { bytes.writeUInt32LE(1, central(bytes) + 42); }],
  ] as const)("refuses %s", async (_name, mutate) => {
    const bytes = archive(); mutate(bytes);
    await expect(openOwnUploadZip(file(bytes), 1000)).rejects.toMatchObject({ code: "archive_invalid" });
  });

  it("rejects truncation, appended junk, empty content and malformed ZIP signatures", async () => {
    const bytes = archive();
    for (const damaged of [bytes.subarray(0, bytes.length - 1), Buffer.concat([bytes, Buffer.from("junk")]),
      archive(Buffer.alloc(0)), Buffer.from("PK\u0003\u0004"), Buffer.alloc(0)]) {
      await expect(openOwnUploadZip(file(damaged), 1000)).rejects.toMatchObject({ code: "archive_invalid" });
    }
    expect(hasZipMagic(raw)).toBe(false);
  });
});
