import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { gzipSync } from "node:zlib";
import { describe, expect, it, vi } from "vitest";
import { ownPreparationOriginalSchema } from "./own-preparation-source";
import { pathBArrayOriginalSchema, readPathBArrayLines, scanPathBArraySource } from "./path-b-array-source";

const sha = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
const cases = [["array_23andme", "23andme.txt"], ["array_ancestry", "ancestry.txt"],
  ["array_myheritage", "myheritage.csv"], ["array_ftdna", "ftdna.csv"]] as const;
function fixture(kind = cases[0][0] as (typeof cases)[number][0], name = cases[0][1] as string, gzip = false,
  text = readFileSync(path.join(process.cwd(), "e2e/fixtures", `path-b-reports-grch38-${name}`), "utf8")) {
  const decoded = Buffer.from(text), bytes = gzip ? gzipSync(decoded) : decoded;
  const source = pathBArrayOriginalSchema.parse({ fileId: "33333333-3333-4333-8333-333333333333",
    subjectId: "44444444-4444-4444-8444-444444444444", objectId: "55555555-5555-4555-8555-555555555555",
    objectKey: "66666666-6666-4666-8666-666666666666", sourceRevision: 1, rawSha256: sha(bytes),
    decodedSha256: sha(decoded), bucket: "genomes", sizeBytes: bytes.length, maximumDecodedBytes: decoded.length,
    fileType: kind });
  const check = vi.fn(async () => {});
  const readRange = vi.fn(async (_source, start: number, end: number) => new Response(Uint8Array.from(bytes.subarray(start, end + 1)),
    { status: 206, headers: { "content-range": `bytes ${start}-${end}/${bytes.length}` } }));
  const controller = new AbortController();
  return { bytes, text, source, check, readRange, controller,
    options: { source, check, readRange, signal: controller.signal } };
}
describe("bounded real Path B array originals", () => {
  it.each(cases)("reverifies complete literal %s bytes on both passes", async (kind, name) => {
    const f = fixture(kind, name); const scan = await scanPathBArraySource(f.options);
    expect(scan.build).toBe("GRCh38"); expect(scan.source).toEqual(f.source);
    const lines: string[] = []; for await (const line of readPathBArrayLines(f.options, scan)) lines.push(line);
    expect(lines.join("\n") + "\n").toBe(f.text);
    expect(f.readRange).toHaveBeenCalledTimes(2); expect(f.check).toHaveBeenCalledTimes(6);
    expect(ownPreparationOriginalSchema.safeParse(f.source).success).toBe(false);
  });
  it.each(cases)("checks actual gzip raw and decoded identity for %s", async (kind, name) => {
    const f = fixture(kind, name, true); const scan = await scanPathBArraySource(f.options);
    expect(scan.compressed).toBe(true); expect(scan.rawSha256).toBe(sha(f.bytes));
    expect(scan.decodedSha256).toBe(sha(Buffer.from(f.text)));
    for await (const line of readPathBArrayLines(f.options, scan)) expect(typeof line).toBe("string");
  });
  it.each(["# Build 99\n", "# Build 37\n"])("refuses an unknown/conflicting complete build %s", async extra => {
    const f = fixture("array_23andme", "23andme.txt", false,
      fixture().text + extra); await expect(scanPathBArraySource(f.options)).rejects.toThrow("unsupported_build");
  });
  it("uses only the existing vendor build37 assumption when no build is declared", async () => {
    const f = fixture("array_23andme", "23andme.txt", false, fixture().text.replace("# Build 38\n", ""));
    expect((await scanPathBArraySource(f.options)).build).toBe("GRCh37");
  });
  it("accepts hg19 as the existing explicit37 spelling", async () => {
    const f = fixture("array_23andme", "23andme.txt", false, fixture().text.replace("Build 38", "hg19"));
    expect((await scanPathBArraySource(f.options)).build).toBe("GRCh37");
  });
  it.each([
    (s: string) => s.replace("# rsid\tchromosome\tposition\tgenotype", "# rsid\tchromosome\tposition\tallele"),
    (s: string) => s + "# rsid\tchromosome\tposition\tgenotype\n",
    (s: string) => s + "rs123\t1\t123\tA\tEXTRA\n",
    (s: string) => s.replace("# This data file generated by 23andMe", "#AncestryDNA"),
  ])("refuses malformed or wrongly declared structural source without changing its hashes", async change => {
    const f = fixture("array_23andme", "23andme.txt", false, change(fixture().text));
    await expect(scanPathBArraySource(f.options)).rejects.toThrow("invalid_array");
  });
  it("refuses current authority before the first network range", async () => {
    const f = fixture(); f.check.mockRejectedValue(new Error("stale authority"));
    await expect(scanPathBArraySource(f.options)).rejects.toThrow("source_unavailable");
    expect(f.readRange).not.toHaveBeenCalled();
  });
  it("refuses a stale authority after the exact downloaded range", async () => {
    const f = fixture(); f.check.mockResolvedValueOnce(undefined).mockRejectedValue(new Error("revoked"));
    await expect(scanPathBArraySource(f.options)).rejects.toThrow("source_unavailable");
    expect(f.readRange).toHaveBeenCalledTimes(1);
  });
  it.each([200, 302, 503])("refuses an inexact range status %s", async status => {
    const f = fixture(); f.readRange.mockResolvedValue(new Response(Uint8Array.from(f.bytes), { status }));
    await expect(scanPathBArraySource(f.options)).rejects.toThrow("invalid_range");
  });
  it("refuses complete source corruption and decoded byte overflow", async () => {
    const f = fixture(); f.source.rawSha256 = "a".repeat(64);
    await expect(scanPathBArraySource(f.options)).rejects.toThrow("integrity_mismatch");
    const small = fixture(); small.source.maximumDecodedBytes--;
    await expect(scanPathBArraySource(small.options)).rejects.toThrow("too_large");
  });
  it("refuses changed bytes at second EOF, not merely a matching first pass", async () => {
    const f = fixture(); const scan = await scanPathBArraySource(f.options);
    const changed = Buffer.from(f.text.replace("CA", "CC"));
    f.readRange.mockResolvedValue(new Response(Uint8Array.from(changed), { status: 206,
      headers: { "content-range": `bytes 0-${changed.length - 1}/${changed.length}` } }));
    await expect((async () => { for await (const line of readPathBArrayLines(f.options, scan)) void line; })())
      .rejects.toThrow("integrity_mismatch");
  });
  it("does no range I/O after an aborted operation", async () => {
    const f = fixture(); f.controller.abort();
    await expect(scanPathBArraySource(f.options)).rejects.toThrow("aborted"); expect(f.readRange).not.toHaveBeenCalled();
  });
});
