import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { describe, expect, it } from "vitest";
import { validateSubjectStructure } from "./subject-structure";
import type { SubjectUploadFormat } from "./subject-upload-contract";

const header = "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tPRIVATE_SAMPLE\n";
// Deliberately not valid genetic calls: structural validation must not parse them.
const row = "opaque\topaque\topaque\topaque\topaque\topaque\topaque\topaque\topaque\topaque\n";
const digest = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
async function* pieces(bytes: Uint8Array, width: number) {
  for (let offset = 0; offset < bytes.length; offset += width) yield bytes.subarray(offset, offset + width);
}
function validate(text: string | Buffer, format: SubjectUploadFormat = "VCF", width = 13,
  patch: Partial<Parameters<typeof validateSubjectStructure>[1]> = {}) {
  const bytes = typeof text === "string" ? Buffer.from(text) : text;
  return validateSubjectStructure(pieces(bytes, width), { declaredFormat: format, expectedSize: bytes.length,
    expectedSha256: digest(bytes), maximumDecodedBytes: 1_000_000, ...patch });
}
describe("complete subject structural validation without genetic interpretation", () => {
  it.each([1, 2, 13, 8192])("hashes every source byte across %s-byte chunks and returns no sample label", async width => {
    const bytes = Buffer.from(header + row);
    const result = await validate(bytes, "VCF", width);
    expect(result).toEqual({ rawSha256: digest(bytes), decodedSha256: digest(bytes), rawBytes: bytes.length,
      decodedBytes: bytes.length, structuralValidatorVersion: "single-logical-sample-v1" });
    expect(JSON.stringify(result)).not.toContain("PRIVATE_SAMPLE");
  });
  it("checks compressed integrity and separately hashes the decoded source", async () => {
    const bytes = Buffer.from(header + row), compressed = gzipSync(bytes);
    const result = await validate(compressed, "VCF.GZ", 1);
    expect(result.rawSha256).toBe(digest(compressed)); expect(result.decodedSha256).toBe(digest(bytes));
  });
  it.each([
    header.replace("\tPRIVATE_SAMPLE", ""), header.replace("PRIVATE_SAMPLE", "PRIVATE_SAMPLE\tSECOND"),
    header + row + header + row, header + row + row.replace("\n", "\textra\n"),
  ])("refuses zero/multiple samples, repeated headers and inconsistent complete rows", async source => {
    await expect(validate(source)).rejects.toMatchObject({ code: "subject_source_not_single_sample" });
  });
  it("sees a second source beyond the sniffer's initial window", async () => {
    await expect(validate(header + row.repeat(1500) + header + row)).rejects.toMatchObject({ code: "subject_source_not_single_sample" });
  });
  it("rejects concatenated compressed datasets and truncated gzip", async () => {
    const gzip = gzipSync(Buffer.from(header + row));
    await expect(validate(Buffer.concat([gzip, gzip]), "VCF.GZ")).rejects.toMatchObject({ code: "subject_source_not_single_sample" });
    await expect(validate(gzip.subarray(0, gzip.length - 5), "VCF.GZ")).rejects.toMatchObject({ code: "unrecognised_format" });
  });
  it("bounds decompression before completing an archive bomb", async () => {
    await expect(validate(gzipSync(Buffer.from(header + row.repeat(100))), "VCF.GZ", 13,
      { maximumDecodedBytes: 1024 })).rejects.toMatchObject({ code: "too_large" });
  });
  it.each([
    ["%PDF-1.7\n", "pdf_not_data"], ["CRAMbinary", "unrecognised_format"],
    ["sample,rsid,genotype\n", "subject_source_not_single_sample"],
    ["not a genetic source", "unrecognised_format"], [row + header, "unrecognised_format"],
  ])("sniffs actual bytes independently of the declared VCF: %s", async (source, code) => {
    await expect(validate(source)).rejects.toMatchObject({ code });
  });
  const arrays: [SubjectUploadFormat, string][] = [
    ["consumer-array-text-v1", "# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\n"],
    ["consumer-array-text-v2", "#AncestryDNA raw data download\nrsid\tchromosome\tposition\tallele1\tallele2\n"],
    ["consumer-array-text-v3", '# A leading comment\n# MyHeritage data\n"RSID","CHROMOSOME","POSITION","RESULT"\n'],
    ["consumer-array-text-v4", "RSID,CHROMOSOME,POSITION,RESULT\n"],
  ];
  it.each(arrays)("accepts one complete %s header but no concatenated source", async (format, prefix) => {
    const data = format === "consumer-array-text-v1" ? "opaque\topaque\topaque\topaque\n"
      : format === "consumer-array-text-v2" ? "opaque\topaque\topaque\topaque\topaque\n" : "opaque,opaque,opaque,opaque\n";
    await expect(validate(prefix + data, format, 1)).resolves.toMatchObject({ rawSha256: digest(Buffer.from(prefix + data)) });
    await expect(validate(prefix + data + prefix + data, format)).rejects.toMatchObject({ code: "subject_source_not_single_sample" });
  });
  it("checks declared length and digest and allows only the explicit missing-hash case", async () => {
    await expect(validate(header + row, "VCF", 13, { expectedSize: 1 })).rejects.toMatchObject({ code: "upload_integrity_mismatch" });
    await expect(validate(header + row, "VCF", 13, { expectedSize: 1000 })).rejects.toMatchObject({ code: "upload_integrity_mismatch" });
    await expect(validate(header + row, "VCF", 13, { expectedSha256: "0".repeat(64) })).rejects.toMatchObject({ code: "upload_integrity_mismatch" });
    await expect(validate(header + row, "VCF", 13, { expectedSha256: null })).resolves.toHaveProperty("rawSha256");
  });
});
