import "server-only";

import { createHash } from "node:crypto";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { createGunzip } from "node:zlib";
import { INGEST_CHUNK_MAXIMUM_BYTES } from "../genome/ingest-limits";
import { sniffHeadV2 } from "../genome/parsers/sniff";
import { declaredSubjectFormat, type SubjectUploadFormat } from "./subject-upload-contract";

export const SUBJECT_STRUCTURE_VERSION = "single-logical-sample-v1";
export type StructureFailure = "upload_integrity_mismatch" | "subject_source_not_single_sample" |
  "pdf_not_data" | "unrecognised_format" | "too_large";
export class SubjectStructureError extends Error {
  constructor(readonly code: StructureFailure) { super(code); this.name = "SubjectStructureError"; }
}
function refuse(code: StructureFailure): never { throw new SubjectStructureError(code); }

/** Complete, bounded structural inspection only. No genotype parser, coordinate
 * inference, variant construction or sample label is returned or persisted. */
export async function validateSubjectStructure(source: AsyncIterable<Uint8Array>, declaration: {
  declaredFormat: SubjectUploadFormat; expectedSize: number; expectedSha256: string | null; maximumDecodedBytes: number;
}) {
  const rawHash = createHash("sha256"), decodedHash = createHash("sha256");
  const iterator = source[Symbol.asyncIterator]();
  let rawBytes = 0, decodedBytes = 0;
  const initial: Uint8Array[] = [];
  let initialLength = 0;
  while (initialLength < 2) {
    const item = await iterator.next(); if (item.done) break;
    initial.push(item.value); initialLength += item.value.length;
  }
  const first = Buffer.concat(initial);
  const compressed = first[0] === 0x1f && first[1] === 0x8b;
  async function* raw() {
    let chunk: Uint8Array | undefined = first;
    while (chunk) {
      rawBytes += chunk.length;
      if (rawBytes > declaration.expectedSize) refuse("upload_integrity_mismatch");
      rawHash.update(chunk); if (chunk.length) yield chunk;
      const next = await iterator.next(); chunk = next.done ? undefined : next.value;
    }
  }
  const input = Readable.from(raw());
  const gunzip = compressed ? createGunzip() : null;
  const transferred = gunzip ? pipeline(input, gunzip) : null;
  // Attach rejection handling before consumption; rethrow below after iteration.
  transferred?.catch(() => {});
  const stream = gunzip ?? input;
  const decoder = new TextDecoder("utf-8", { fatal: true });
  let carry = "", head = Buffer.alloc(0), structuralHeaders = 0, formatMarkers = 0, sawData = false;
  const pendingComments: string[] = [];
  let kind: ReturnType<typeof sniffHeadV2>["kind"] = null;
  function inspect(line: string) {
    line = line.replace(/\r$/, ""); if (!line) return;
    if (Buffer.byteLength(line) > INGEST_CHUNK_MAXIMUM_BYTES) refuse("unrecognised_format");
    if (!kind) kind = sniffHeadV2(head, compressed).kind;
    if (!kind && head.length < 65536 && line.startsWith("#")) { pendingComments.push(line); return; }
    if (kind === "pdf") refuse("pdf_not_data");
    if (kind === "pgt_table" || kind === "vcf_multisample") refuse("subject_source_not_single_sample");
    if (!kind || kind === "bam" || kind === "cram") refuse("unrecognised_format");
    for (const pending of pendingComments.splice(0)) inspect(pending);
    const isVcf = kind === "vcf" || kind === "gvcf";
    const format = declaredSubjectFormat(kind, compressed);
    if (isVcf ? !["VCF", "VCF.GZ", "gVCF"].includes(declaration.declaredFormat)
      || (declaration.declaredFormat === "VCF.GZ" && !compressed)
      || (declaration.declaredFormat === "VCF" && compressed) : format !== declaration.declaredFormat) refuse("unrecognised_format");
    if (/^(?:##fileformat=|# This data file generated by |#AncestryDNA)/.test(line)) {
      if (++formatMarkers > 1 || structuralHeaders || sawData) refuse("subject_source_not_single_sample");
    }
    if (isVcf) {
      if (line.startsWith("#CHROM")) {
        if (++structuralHeaders !== 1 || sawData) refuse("subject_source_not_single_sample");
        const columns = line.split("\t");
        if (columns.length !== 10 || !columns[9]?.trim()) refuse("subject_source_not_single_sample");
        if (columns.slice(0, 9).join("\t") !== "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT") refuse("unrecognised_format");
      } else if (!line.startsWith("#")) {
        if (structuralHeaders !== 1 || line.split("\t").length !== 10) refuse("subject_source_not_single_sample");
        sawData = true;
      } else if (sawData) refuse("subject_source_not_single_sample");
      return;
    }
    const columns = line.replace(/^#\s*/, "").split(kind === "array_myheritage" || kind === "array_ftdna" ? "," : "\t");
    if (columns[0]?.replace(/^"|"$/g, "").trim().toLowerCase() === "rsid") {
      if (++structuralHeaders !== 1 || sawData) refuse("subject_source_not_single_sample");
      const expected = kind === "array_ancestry" ? ["rsid", "chromosome", "position", "allele1", "allele2"]
        : ["rsid", "chromosome", "position", kind === "array_23andme" ? "genotype" : "result"];
      if (columns.map(column => column.replace(/^"|"$/g, "").trim().toLowerCase()).join("|") !== expected.join("|")) refuse("unrecognised_format");
    } else if (!line.startsWith("#")) {
      if (structuralHeaders !== 1 || columns.length !== (kind === "array_ancestry" ? 5 : 4)) refuse("subject_source_not_single_sample");
      sawData = true;
    }
  }
  try {
    for await (const value of stream) {
      const chunk = value as Buffer;
      decodedBytes += chunk.length;
      if (decodedBytes > declaration.maximumDecodedBytes) refuse("too_large");
      decodedHash.update(chunk);
      if (head.length < 65536) head = Buffer.concat([head, chunk.subarray(0, 65536 - head.length)]);
      if (head.subarray(0, 5).toString("ascii") === "%PDF-") refuse("pdf_not_data");
      carry += decoder.decode(chunk, { stream: true });
      let at: number;
      while ((at = carry.indexOf("\n")) !== -1) { inspect(carry.slice(0, at)); carry = carry.slice(at + 1); }
      if (Buffer.byteLength(carry) > INGEST_CHUNK_MAXIMUM_BYTES) refuse("unrecognised_format");
    }
    carry += decoder.decode(); if (carry) inspect(carry);
    if (transferred) await transferred;
    const rawSha256 = rawHash.digest("hex");
    if (rawBytes !== declaration.expectedSize || (declaration.expectedSha256 !== null && rawSha256 !== declaration.expectedSha256)) {
      refuse("upload_integrity_mismatch");
    }
    if (!kind) refuse("unrecognised_format");
    if (structuralHeaders !== 1) refuse("subject_source_not_single_sample");
    return { rawSha256, decodedSha256: decodedHash.digest("hex"), rawBytes, decodedBytes,
      structuralValidatorVersion: SUBJECT_STRUCTURE_VERSION };
  } catch (error) {
    if (error instanceof SubjectStructureError) throw error;
    const code = (error as { code?: string } | null)?.code;
    if (code === "Z_DATA_ERROR" || code === "Z_BUF_ERROR" || code === "ERR_ENCODING_INVALID_ENCODED_DATA") refuse("unrecognised_format");
    throw error;
  } finally {
    input.destroy(); gunzip?.destroy();
    if (transferred) await transferred.catch(() => {});
    await iterator.return?.();
  }
}
